from django.conf.urls import patterns, url
from accounts import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.login, name='login'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^activate_users/$', views.activate_users, name='activate_users'),
    url(r'^activate_user/(?P<user_id>\d+)$', views.activate_user, name='activate_user'),

    url(r'^logout/$', 'django.contrib.auth.views.logout',
        kwargs={'template_name': 'accounts/logged_out.html'}),
    # copied from contrib/auth/urls.py
    url(r'^password_change/$',
        'django.contrib.auth.views.password_change',
        name='password_change',
        kwargs={'template_name': 'accounts/password_change_form.html'}),
    url(r'^password_change/done/$',
        'django.contrib.auth.views.password_change_done',
        name='password_change_done',
        kwargs={'template_name': 'accounts/password_change_done.html'}),
    url(r'^password_reset/$',
        'django.contrib.auth.views.password_reset',
        name='password_reset',
        kwargs={'template_name': 'accounts/password_reset_form.html',
                'email_template_name': 'accounts/password_reset_email.html'}),
    url(r'^password_reset/done/$',
        'django.contrib.auth.views.password_reset_done',
        name='password_reset_done',
        kwargs={'template_name': 'accounts/password_reset_done.html'}),
    # Support old style base36 password reset links; remove in Django 1.7
    url(r'^reset/(?P<uidb36>[0-9A-Za-z]{1,13})-(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        'django.contrib.auth.views.password_reset_confirm_uidb36',
        kwargs={'template_name': 'accounts/password_reset_confirm.html'}),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        'django.contrib.auth.views.password_reset_confirm',
        name='password_reset_confirm',
        kwargs={'template_name': 'accounts/password_reset_confirm.html'}),
    url(r'^reset/done/$',
        'django.contrib.auth.views.password_reset_complete',
        name='password_reset_complete',
        kwargs={'template_name': 'accounts/password_reset_complete.html'}),
)
