# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-18 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lbwuser',
            name='profile_image',
            field=models.ImageField(default='img/unknown.jpg', upload_to='img/'),
        ),
    ]
